# ======================== PRESETS DE REQUERIMIENTOS NUTRICIONALES ========================
# Estructura: PRESETS[especie][etapa][nutriente] = {"min": valor}
# Los nutrientes usan los mismos nombres de columna que la matriz de ingredientes.
# Nota: los valores serán ajustados con datos de referencia en fases posteriores.

PRESETS = {
    "Aves": {
        "Broiler Iniciación": {
            "EMA_POLLIT":  {"min": 2950},
            "PB":          {"min": 21.2},
            "FB":          {"min": 2.85},
            "LYS_DIS":     {"min": 1.22},
            "MET_DIS":     {"min": 0.49},
            "M+C_DIS":     {"min": 0.90},
            "THR_DIS":     {"min": 0.79},
            "TRP_DIS":     {"min": 0.21},
            "ILE_DIS":     {"min": 0.82},
            "VAL_DIS":     {"min": 0.96},
            "ARG_DIS":     {"min": 1.28},
            "Ca":          {"min": 0.98},
            "P":           {"min": 0.66},
            "Pdisp.AVES":  {"min": 0.48},
            "Na":          {"min": 0.19},
            "K":           {"min": 0.51},
            "Cl":          {"min": 0.17},
            "Zn":          {"min": 75},
            "Cu":          {"min": 8},
            "Mn":          {"min": 90},
            "Fe":          {"min": 33},
            "Vit. E":      {"min": 20},
            "Colina":      {"min": 1250},
            "Biotina":     {"min": 130},
        },
        "Broiler Crecimiento": {
            "EMA_AVES":    {"min": 3050},
            "PB":          {"min": 20.0},
            "FB":          {"min": 3.0},
            "LYS_DIS":     {"min": 1.10},
            "MET_DIS":     {"min": 0.45},
            "M+C_DIS":     {"min": 0.84},
            "THR_DIS":     {"min": 0.73},
            "TRP_DIS":     {"min": 0.20},
            "ILE_DIS":     {"min": 0.75},
            "VAL_DIS":     {"min": 0.87},
            "ARG_DIS":     {"min": 1.17},
            "Ca":          {"min": 0.90},
            "P":           {"min": 0.58},
            "Pdisp.AVES":  {"min": 0.43},
            "Na":          {"min": 0.17},
            "K":           {"min": 0.50},
            "Cl":          {"min": 0.17},
            "Zn":          {"min": 65},
            "Cu":          {"min": 7},
            "Mn":          {"min": 70},
            "Fe":          {"min": 30},
            "Vit. E":      {"min": 15},
            "Colina":      {"min": 1200},
            "Biotina":     {"min": 100},
        },
        "Broiler Cebo": {
            "EMA_AVES":    {"min": 3100},
            "PB":          {"min": 18.5},
            "FB":          {"min": 3.05},
            "LYS_DIS":     {"min": 1.00},
            "MET_DIS":     {"min": 0.41},
            "M+C_DIS":     {"min": 0.76},
            "THR_DIS":     {"min": 0.66},
            "TRP_DIS":     {"min": 0.18},
            "ILE_DIS":     {"min": 0.68},
            "VAL_DIS":     {"min": 0.79},
            "ARG_DIS":     {"min": 1.06},
            "Ca":          {"min": 0.75},
            "P":           {"min": 0.56},
            "Pdisp.AVES":  {"min": 0.38},
            "Na":          {"min": 0.16},
            "K":           {"min": 0.46},
            "Cl":          {"min": 0.16},
            "Zn":          {"min": 65},
            "Cu":          {"min": 7},
            "Mn":          {"min": 70},
            "Fe":          {"min": 30},
            "Vit. E":      {"min": 15},
            "Colina":      {"min": 1200},
            "Biotina":     {"min": 100},
        },
        "Broiler Acabado": {
            "EMA_AVES":    {"min": 3120},
            "PB":          {"min": 17.5},
            "FB":          {"min": 3.05},
            "LYS_DIS":     {"min": 0.92},
            "MET_DIS":     {"min": 0.38},
            "M+C_DIS":     {"min": 0.70},
            "THR_DIS":     {"min": 0.61},
            "TRP_DIS":     {"min": 0.17},
            "ILE_DIS":     {"min": 0.63},
            "VAL_DIS":     {"min": 0.73},
            "ARG_DIS":     {"min": 0.98},
            "Ca":          {"min": 0.70},
            "P":           {"min": 0.52},
            "Pdisp.AVES":  {"min": 0.35},
            "Na":          {"min": 0.15},
            "K":           {"min": 0.40},
            "Cl":          {"min": 0.15},
            "Zn":          {"min": 45},
            "Cu":          {"min": 4},
            "Mn":          {"min": 55},
            "Fe":          {"min": 25},
            "Vit. E":      {"min": 12},
            "Colina":      {"min": 1100},
            "Biotina":     {"min": 10},
        },
        "Pollita Recría 0-5": {
            "EMA_AVES":    {"min": 2960},
            "PB":          {"min": 18.8},
            "FB":          {"min": 3.3},
            "LYS_DIS":     {"min": 0.98},
            "MET_DIS":     {"min": 0.43},
            "M+C_DIS":     {"min": 0.74},
            "THR_DIS":     {"min": 0.65},
            "TRP_DIS":     {"min": 0.19},
            "ILE_DIS":     {"min": 0.67},
            "VAL_DIS":     {"min": 0.74},
            "ARG_DIS":     {"min": 1.03},
            "Ca":          {"min": 0.90},
            "P":           {"min": 0.62},
            "Pdisp.AVES":  {"min": 0.43},
            "Na":          {"min": 0.19},
            "K":           {"min": 0.50},
            "Cl":          {"min": 0.15},
            "Zn":          {"min": 50},
            "Cu":          {"min": 5},
            "Mn":          {"min": 60},
            "Fe":          {"min": 35},
            "Vit. E":      {"min": 10},
            "Colina":      {"min": 1260},
            "Biotina":     {"min": 50},
        },
        "Pollita Recría 5-10": {
            "EMA_AVES":    {"min": 2820},
            "PB":          {"min": 16.7},
            "FB":          {"min": 3.6},
            "LYS_DIS":     {"min": 0.76},
            "MET_DIS":     {"min": 0.34},
            "M+C_DIS":     {"min": 0.61},
            "THR_DIS":     {"min": 0.52},
            "TRP_DIS":     {"min": 0.15},
            "ILE_DIS":     {"min": 0.53},
            "VAL_DIS":     {"min": 0.58},
            "ARG_DIS":     {"min": 0.80},
            "Ca":          {"min": 0.80},
            "P":           {"min": 0.49},
            "Pdisp.AVES":  {"min": 0.40},
            "Na":          {"min": 0.17},
            "K":           {"min": 0.50},
            "Cl":          {"min": 0.15},
            "Zn":          {"min": 40},
            "Cu":          {"min": 6},
            "Mn":          {"min": 50},
            "Fe":          {"min": 35},
            "Vit. E":      {"min": 10},
            "Colina":      {"min": 1230},
            "Biotina":     {"min": 30},
        },
        "Pollita Recría 10-17": {
            "EMA_AVES":    {"min": 2730},
            "PB":          {"min": 15.0},
            "FB":          {"min": 4.0},
            "LYS_DIS":     {"min": 0.55},
            "MET_DIS":     {"min": 0.26},
            "M+C_DIS":     {"min": 0.46},
            "THR_DIS":     {"min": 0.40},
            "TRP_DIS":     {"min": 0.12},
            "ILE_DIS":     {"min": 0.39},
            "VAL_DIS":     {"min": 0.42},
            "ARG_DIS":     {"min": 0.58},
            "Ca":          {"min": 0.75},
            "P":           {"min": 0.48},
            "Pdisp.AVES":  {"min": 0.37},
            "Na":          {"min": 0.15},
            "K":           {"min": 0.48},
            "Cl":          {"min": 0.15},
            "Zn":          {"min": 40},
            "Cu":          {"min": 6},
            "Mn":          {"min": 50},
            "Fe":          {"min": 35},
            "Vit. E":      {"min": 10},
            "Colina":      {"min": 1200},
            "Biotina":     {"min": 30},
        },
        "Pollita Inicio Puesta": {
            "EMA_AVES":    {"min": 2730},
            "PB":          {"min": 17.0},
            "FB":          {"min": 3.5},
            "LYS_DIS":     {"min": 0.68},
            "MET_DIS":     {"min": 0.34},
            "M+C_DIS":     {"min": 0.60},
            "THR_DIS":     {"min": 0.48},
            "TRP_DIS":     {"min": 0.14},
            "ILE_DIS":     {"min": 0.54},
            "VAL_DIS":     {"min": 0.61},
            "ARG_DIS":     {"min": 0.71},
            "Ca":          {"min": 2.85},
            "P":           {"min": 0.59},
            "Pdisp.AVES":  {"min": 0.39},
            "Na":          {"min": 0.16},
            "K":           {"min": 0.50},
            "Cl":          {"min": 0.16},
            "Zn":          {"min": 40},
            "Cu":          {"min": 6},
            "Mn":          {"min": 50},
            "Fe":          {"min": 35},
            "Vit. E":      {"min": 10},
            "Colina":      {"min": 1200},
            "Biotina":     {"min": 30},
        },
        "Ponedora Pre-Pico": {
            "EMA_AVES":    {"min": 2750},
            "PB":          {"min": 16.5},
            "FB":          {"min": 3.5},
            "LYS_DIS":     {"min": 0.74},
            "MET_DIS":     {"min": 0.36},
            "M+C_DIS":     {"min": 0.66},
            "THR_DIS":     {"min": 0.52},
            "TRP_DIS":     {"min": 0.16},
            "ILE_DIS":     {"min": 0.58},
            "VAL_DIS":     {"min": 0.66},
            "ARG_DIS":     {"min": 0.80},
            "Ca":          {"min": 2.70},
            "P":           {"min": 0.58},
            "Pdisp.AVES":  {"min": 0.38},
            "Na":          {"min": 0.16},
            "K":           {"min": 0.50},
            "Cl":          {"min": 0.16},
            "Zn":          {"min": 55},
            "Cu":          {"min": 8},
            "Mn":          {"min": 70},
            "Fe":          {"min": 35},
            "Vit. E":      {"min": 15},
            "Colina":      {"min": 1100},
            "Biotina":     {"min": 30},
        },
        "Ponedora Inicio Postura": {
            "EMA_AVES":    {"min": 2720},
            "PB":          {"min": 15.8},
            "FB":          {"min": 3.8},
            "LYS_DIS":     {"min": 0.70},
            "MET_DIS":     {"min": 0.34},
            "M+C_DIS":     {"min": 0.62},
            "THR_DIS":     {"min": 0.50},
            "TRP_DIS":     {"min": 0.15},
            "ILE_DIS":     {"min": 0.55},
            "VAL_DIS":     {"min": 0.62},
            "ARG_DIS":     {"min": 0.75},
            "Ca":          {"min": 3.90},
            "P":           {"min": 0.55},
            "Pdisp.AVES":  {"min": 0.35},
            "Na":          {"min": 0.16},
            "K":           {"min": 0.48},
            "Cl":          {"min": 0.16},
            "Zn":          {"min": 55},
            "Cu":          {"min": 8},
            "Mn":          {"min": 70},
            "Fe":          {"min": 35},
            "Vit. E":      {"min": 15},
            "Colina":      {"min": 1000},
            "Biotina":     {"min": 30},
        },
        "Ponedora Final Postura": {
            "EMA_AVES":    {"min": 2680},
            "PB":          {"min": 15.0},
            "FB":          {"min": 4.0},
            "LYS_DIS":     {"min": 0.64},
            "MET_DIS":     {"min": 0.31},
            "M+C_DIS":     {"min": 0.58},
            "THR_DIS":     {"min": 0.47},
            "TRP_DIS":     {"min": 0.14},
            "ILE_DIS":     {"min": 0.51},
            "VAL_DIS":     {"min": 0.58},
            "ARG_DIS":     {"min": 0.70},
            "Ca":          {"min": 4.20},
            "P":           {"min": 0.52},
            "Pdisp.AVES":  {"min": 0.33},
            "Na":          {"min": 0.16},
            "K":           {"min": 0.46},
            "Cl":          {"min": 0.16},
            "Zn":          {"min": 60},
            "Cu":          {"min": 8},
            "Mn":          {"min": 75},
            "Fe":          {"min": 35},
            "Vit. E":      {"min": 20},
            "Colina":      {"min": 950},
            "Biotina":     {"min": 35},
        },
        "Ponedora Problemas Cascara": {
            "EMA_AVES":    {"min": 2680},
            "PB":          {"min": 15.0},
            "FB":          {"min": 4.0},
            "LYS_DIS":     {"min": 0.64},
            "MET_DIS":     {"min": 0.31},
            "M+C_DIS":     {"min": 0.58},
            "THR_DIS":     {"min": 0.47},
            "TRP_DIS":     {"min": 0.14},
            "ILE_DIS":     {"min": 0.51},
            "VAL_DIS":     {"min": 0.58},
            "ARG_DIS":     {"min": 0.70},
            "Ca":          {"min": 4.50},
            "P":           {"min": 0.50},
            "Pdisp.AVES":  {"min": 0.30},
            "Na":          {"min": 0.16},
            "K":           {"min": 0.46},
            "Cl":          {"min": 0.16},
            "Zn":          {"min": 80},
            "Cu":          {"min": 10},
            "Mn":          {"min": 90},
            "Fe":          {"min": 35},
            "Vit. E":      {"min": 25},
            "Colina":      {"min": 950},
            "Biotina":     {"min": 40},
        },
    },
    "Cerdos": {
        "Adultos - Gestación estándar": {
            "EM_PORC":     {"min": 2875},
            "EN_CERDAS":   {"min": 2130},
            "EE":          {"min": 3.1},
            "FB":          {"min": 6.0, "max": 10.0},
            "FND":         {"min": 18.0},
            "PB":          {"min": 13.7, "max": 15.8},
            "LYS_DIS":     {"min": 0.51},
            "MET_DIS":     {"min": 0.16},
            "M+C_DIS":     {"min": 0.34},
            "THR_DIS":     {"min": 0.37},
            "TRP_DIS":     {"min": 0.10},
            "VAL_DIS":     {"min": 0.36},
            "ILE_DIS":     {"min": 0.31},
            "Ca":          {"min": 0.81, "max": 1.05},
            "P":           {"min": 0.60},
            "Pdig.PORC":   {"min": 0.29},
            "Na":          {"min": 0.18},
            "Cl":          {"min": 0.16},
            "K":           {"min": 0.25, "max": 1.10},
            "Vit. E":      {"min": 35, "max": 70},
            "Biotina":     {"min": 120, "max": 250},
            "Colina":      {"min": 200, "max": 400},
            "Fe":          {"min": 60, "max": 95},
            "Cu":          {"min": 10, "max": 15},
            "Zn":          {"min": 95, "max": 120},
            "Mn":          {"min": 40, "max": 50},
        },
        "Adultos - Lactación estándar": {
            "EM_PORC":     {"min": 2980},
            "EN_CERDAS":   {"min": 2250},
            "EE":          {"min": 5.4},
            "FB":          {"min": 4.6, "max": 7.2},
            "FND":         {"min": 15.0},
            "PB":          {"min": 16.4, "max": 17.5},
            "LYS_DIS":     {"min": 0.84},
            "MET_DIS":     {"min": 0.25},
            "M+C_DIS":     {"min": 0.47},
            "THR_DIS":     {"min": 0.55},
            "TRP_DIS":     {"min": 0.16},
            "VAL_DIS":     {"min": 0.67},
            "ILE_DIS":     {"min": 0.48},
            "Ca":          {"min": 0.95, "max": 1.05},
            "P":           {"min": 0.66},
            "Pdig.PORC":   {"min": 0.32},
            "Na":          {"min": 0.19},
            "Cl":          {"min": 0.17},
            "K":           {"min": 0.28, "max": 1.10},
            "Vit. E":      {"min": 35, "max": 70},
            "Biotina":     {"min": 120, "max": 250},
            "Colina":      {"min": 200, "max": 400},
            "Fe":          {"min": 60, "max": 95},
            "Cu":          {"min": 10, "max": 15},
            "Zn":          {"min": 95, "max": 120},
            "Mn":          {"min": 40, "max": 50},
        },
        "Adultos - Verracos": {
            "EM_PORC":     {"min": 2930},
            "EN_CERDAS":   {"min": 2150},
            "EE":          {"min": 3.0},
            "FB":          {"min": 6.5, "max": 10.0},
            "FND":         {"min": 19.0},
            "PB":          {"min": 14.8, "max": 16.0},
            "LYS_DIS":     {"min": 0.55},
            "MET_DIS":     {"min": 0.17},
            "M+C_DIS":     {"min": 0.36},
            "THR_DIS":     {"min": 0.40},
            "TRP_DIS":     {"min": 0.11},
            "VAL_DIS":     {"min": 0.39},
            "ILE_DIS":     {"min": 0.33},
            "Ca":          {"min": 0.85, "max": 1.00},
            "P":           {"min": 0.65},
            "Pdig.PORC":   {"min": 0.31},
            "Na":          {"min": 0.17},
            "Cl":          {"min": 0.15},
            "K":           {"min": 0.27, "max": 1.00},
            "Vit. E":      {"min": 40, "max": 65},
            "Biotina":     {"min": 150, "max": 320},
            "Colina":      {"min": 250, "max": 450},
            "Fe":          {"min": 60, "max": 90},
            "Cu":          {"min": 8, "max": 15},
            "Zn":          {"min": 95, "max": 140},
            "Mn":          {"min": 25, "max": 50},
        },
        "Lechones - Preiniciador": {
            "EM_PORC":     {"min": 3400},
            "EN_PORC":     {"min": 2550},
            "EE":          {"min": 5.5},
            "FB":          {"min": 2.0, "max": 4.0},
            "FND":         {"min": 7.0},
            "PB":          {"min": 20.5, "max": 22.5},
            "LYS_DIS":     {"min": 1.45},
            "MET_DIS":     {"min": 0.44},
            "M+C_DIS":     {"min": 0.81},
            "THR_DIS":     {"min": 0.90},
            "TRP_DIS":     {"min": 0.27},
            "VAL_DIS":     {"min": 0.93},
            "ILE_DIS":     {"min": 0.74},
            "ARG_DIS":     {"min": 1.15},
            "Ca":          {"min": 0.85, "max": 0.95},
            "P":           {"min": 0.68},
            "Pdig.PORC":   {"min": 0.42},
            "Na":          {"min": 0.22},
            "Cl":          {"min": 0.20},
            "K":           {"min": 0.30, "max": 1.10},
            "Vit. E":      {"min": 80, "max": 150},
            "Biotina":     {"min": 180, "max": 350},
            "Colina":      {"min": 500, "max": 900},
            "Fe":          {"min": 100, "max": 150},
            "Cu":          {"min": 120, "max": 160},
            "Zn":          {"min": 120, "max": 180},
            "Mn":          {"min": 40, "max": 60},
        },
        "Lechones - Inicio": {
            "EM_PORC":     {"min": 3350},
            "EN_PORC":     {"min": 2480},
            "EE":          {"min": 4.5},
            "FB":          {"min": 2.5, "max": 5.0},
            "FND":         {"min": 9.0},
            "PB":          {"min": 19.0, "max": 21.0},
            "LYS_DIS":     {"min": 1.30},
            "MET_DIS":     {"min": 0.40},
            "M+C_DIS":     {"min": 0.74},
            "THR_DIS":     {"min": 0.81},
            "TRP_DIS":     {"min": 0.24},
            "VAL_DIS":     {"min": 0.83},
            "ILE_DIS":     {"min": 0.66},
            "ARG_DIS":     {"min": 1.02},
            "Ca":          {"min": 0.78, "max": 0.90},
            "P":           {"min": 0.62},
            "Pdig.PORC":   {"min": 0.38},
            "Na":          {"min": 0.20},
            "Cl":          {"min": 0.18},
            "K":           {"min": 0.28, "max": 1.05},
            "Vit. E":      {"min": 70, "max": 130},
            "Biotina":     {"min": 160, "max": 320},
            "Colina":      {"min": 450, "max": 800},
            "Fe":          {"min": 90, "max": 140},
            "Cu":          {"min": 100, "max": 150},
            "Zn":          {"min": 110, "max": 170},
            "Mn":          {"min": 35, "max": 55},
        },
        "Lechones - Crecimiento temprano": {
            "EM_PORC":     {"min": 3300},
            "EN_PORC":     {"min": 2430},
            "EE":          {"min": 3.8},
            "FB":          {"min": 3.0, "max": 5.5},
            "FND":         {"min": 10.0},
            "PB":          {"min": 17.5, "max": 19.5},
            "LYS_DIS":     {"min": 1.10},
            "MET_DIS":     {"min": 0.35},
            "M+C_DIS":     {"min": 0.66},
            "THR_DIS":     {"min": 0.70},
            "TRP_DIS":     {"min": 0.21},
            "VAL_DIS":     {"min": 0.72},
            "ILE_DIS":     {"min": 0.57},
            "ARG_DIS":     {"min": 0.90},
            "Ca":          {"min": 0.72, "max": 0.85},
            "P":           {"min": 0.58},
            "Pdig.PORC":   {"min": 0.34},
            "Na":          {"min": 0.18},
            "Cl":          {"min": 0.17},
            "K":           {"min": 0.26, "max": 1.00},
            "Vit. E":      {"min": 50, "max": 110},
            "Biotina":     {"min": 140, "max": 280},
            "Colina":      {"min": 400, "max": 700},
            "Fe":          {"min": 80, "max": 130},
            "Cu":          {"min": 80, "max": 130},
            "Zn":          {"min": 100, "max": 160},
            "Mn":          {"min": 30, "max": 50},
        },
        "Cerdos - Crecimiento 20-60 kg": {
            "EM_PORC":     {"min": 3180},
            "EN_PORC":     {"min": 2400},
            "EE":          {"min": 4, "max": 8},
            "FB":          {"min": 3.4, "max": 5.4},
            "FND":         {"min": 11, "max": 15.5},
            "PB":          {"min": 16.2, "max": 18.0},
            "LYS_DIS":     {"min": 0.89},
            "MET_DIS":     {"min": 0.28},
            "M+C_DIS":     {"min": 0.53},
            "THR_DIS":     {"min": 0.58},
            "TRP_DIS":     {"min": 0.17},
            "VAL_DIS":     {"min": 0.60},
            "ILE_DIS":     {"min": 0.49},
            "Ca":          {"min": 0.67, "max": 0.80},
            "P":           {"min": 0.55},
            "Pdig.PORC":   {"min": 0.28},
            "Na":          {"min": 0.18},
            "Cl":          {"min": 0.15},
            "K":           {"min": 0.26, "max": 1.05},
            "Vit. E":      {"min": 15, "max": 30},
            "Biotina":     {"min": 10, "max": 50},
            "Colina":      {"min": 50, "max": 110},
            "Fe":          {"min": 70, "max": 100},
            "Cu":          {"min": 9, "max": 13},
            "Zn":          {"min": 110, "max": 120},
            "Mn":          {"min": 25, "max": 45},
        },
        "Cerdos - Engorde 60-100 kg": {
            "EM_PORC":     {"min": 3175},
            "EN_PORC":     {"min": 2400},
            "EE":          {"min": 4, "max": 8},
            "FB":          {"min": 3.5, "max": 6.3},
            "FND":         {"min": 11, "max": 15.5},
            "PB":          {"min": 14.8, "max": 17.0},
            "LYS_DIS":     {"min": 0.77},
            "MET_DIS":     {"min": 0.24},
            "M+C_DIS":     {"min": 0.46},
            "THR_DIS":     {"min": 0.50},
            "TRP_DIS":     {"min": 0.15},
            "VAL_DIS":     {"min": 0.52},
            "ILE_DIS":     {"min": 0.42},
            "Ca":          {"min": 0.65, "max": 0.80},
            "P":           {"min": 0.53},
            "Pdig.PORC":   {"min": 0.25},
            "Na":          {"min": 0.17},
            "Cl":          {"min": 0.14},
            "K":           {"min": 0.25, "max": 1.05},
            "Vit. E":      {"min": 12, "max": 25},
            "Biotina":     {"min": 0, "max": 25},
            "Colina":      {"min": 40, "max": 100},
            "Fe":          {"min": 50, "max": 90},
            "Cu":          {"min": 8, "max": 10},
            "Zn":          {"min": 90, "max": 110},
            "Mn":          {"min": 18, "max": 35},
        },
        "Cerdos - Acabado >100 kg": {
            "EM_PORC":     {"min": 3150},
            "EN_PORC":     {"min": 2400},
            "EE":          {"min": 4, "max": 8},
            "FB":          {"min": 3.7, "max": 6.5},
            "FND":         {"min": 11, "max": 16.5},
            "PB":          {"min": 13.2, "max": 15.1},
            "LYS_DIS":     {"min": 0.63},
            "MET_DIS":     {"min": 0.20},
            "M+C_DIS":     {"min": 0.38},
            "THR_DIS":     {"min": 0.42},
            "TRP_DIS":     {"min": 0.12},
            "VAL_DIS":     {"min": 0.42},
            "ILE_DIS":     {"min": 0.35},
            "Ca":          {"min": 0.59, "max": 0.80},
            "P":           {"min": 0.49},
            "Pdig.PORC":   {"min": 0.23},
            "Na":          {"min": 0.16},
            "Cl":          {"min": 0.12},
            "K":           {"min": 0.24, "max": 1.10},
            "Vit. E":      {"min": 12, "max": 25},
            "Biotina":     {"min": 0, "max": 25},
            "Colina":      {"min": 40, "max": 100},
            "Fe":          {"min": 50, "max": 90},
            "Cu":          {"min": 8, "max": 10},
            "Zn":          {"min": 90, "max": 110},
            "Mn":          {"min": 18, "max": 35},
        },
    },
    "Rumiantes": {
        "Terneros": {
            "PB":          {"min": 16.0},
            "EE":          {"min": 2.0},
            "FB":          {"min": 12.0},
            "Ca":          {"min": 0.65},
            "P":           {"min": 0.40},
            "Na":          {"min": 0.10},
        },
        "Vacas lecheras": {
            "PB":          {"min": 16.0},
            "EE":          {"min": 3.0},
            "FB":          {"min": 17.0},
            "Ca":          {"min": 0.60},
            "P":           {"min": 0.35},
            "Na":          {"min": 0.18},
        },
        "Vacas secas": {
            "PB":          {"min": 12.0},
            "EE":          {"min": 2.0},
            "FB":          {"min": 18.0},
            "Ca":          {"min": 0.40},
            "P":           {"min": 0.20},
            "Na":          {"min": 0.10},
        },
    },
}
