# ======================== PRESETS DE REQUERIMIENTOS NUTRICIONALES ========================
# Estructura: PRESETS[especie][etapa][nutriente] = {"min": valor, "max": valor}
# Los nutrientes usan los mismos nombres de columna que la matriz de ingredientes.
# Los valores None indican que el límite no aplica para esa especie/etapa.
# Nota: los valores serán ajustados con datos de referencia en fases posteriores.

PRESETS = {
    "Aves": {
        "Broiler Iniciación": {
            "EMA_POLLIT":  {"min": 2950,      "max": 2950},
            "PB":          {"min": 21.2,      "max": None},
            "FB":          {"min": 2.85,      "max": 3.87},
            "LYS_DR":      {"min": 1.22,      "max": None},
            "MET_DR":      {"min": 0.49,      "max": None},
            "M+C_DR":      {"min": 0.90,      "max": None},
            "THR_DR":      {"min": 0.79,      "max": None},
            "TRP_DR":      {"min": 0.21,      "max": None},
            "ILE_DR":      {"min": 0.82,      "max": None},
            "VAL_DR":      {"min": 0.96,      "max": None},
            "ARG_DR":      {"min": 1.28,      "max": None},
            "Ca":          {"min": 0.98,      "max": 1.05},
            "P":           {"min": 0.66,      "max": None},
            "Pdisp.AVES":  {"min": 0.48,      "max": None},
            "Na":          {"min": 0.19,      "max": 0.23},
            "K":           {"min": 0.51,      "max": 1.15},
            "Cl":          {"min": 0.17,      "max": 0.27},
            "Zn":          {"min": 75,        "max": 80},
            "Cu":          {"min": 8,         "max": 10},
            "Mn":          {"min": 90,        "max": 120},
            "Fe":          {"min": 33,        "max": 50},
            "Vit. E":      {"min": 20,        "max": 50},
            "Colina":      {"min": 0.125,     "max": 0.125},
            "Biotina":     {"min": 0.000013,  "max": 0.000018},
        },
        "Broiler Crecimiento": {
            "EMA_AVES":    {"min": 3050,      "max": 3050},
            "PB":          {"min": 20.0,      "max": None},
            "FB":          {"min": 3.0,       "max": 4.1},
            "LYS_DR":      {"min": 1.10,      "max": None},
            "MET_DR":      {"min": 0.45,      "max": None},
            "M+C_DR":      {"min": 0.84,      "max": None},
            "THR_DR":      {"min": 0.73,      "max": None},
            "TRP_DR":      {"min": 0.20,      "max": None},
            "ILE_DR":      {"min": 0.75,      "max": None},
            "VAL_DR":      {"min": 0.87,      "max": None},
            "ARG_DR":      {"min": 1.17,      "max": None},
            "Ca":          {"min": 0.90,      "max": 0.95},
            "P":           {"min": 0.58,      "max": None},
            "Pdisp.AVES":  {"min": 0.43,      "max": None},
            "Na":          {"min": 0.17,      "max": 0.20},
            "K":           {"min": 0.50,      "max": 1.10},
            "Cl":          {"min": 0.17,      "max": 0.28},
            "Zn":          {"min": 65,        "max": 80},
            "Cu":          {"min": 7,         "max": 8},
            "Mn":          {"min": 70,        "max": 105},
            "Fe":          {"min": 30,        "max": 40},
            "Vit. E":      {"min": 15,        "max": 40},
            "Colina":      {"min": 0.120,     "max": 0.120},
            "Biotina":     {"min": 0.000010,  "max": 0.000013},
        },
        "Broiler Cebo": {
            "EMA_AVES":    {"min": 3100,      "max": 3100},
            "PB":          {"min": 18.5,      "max": None},
            "FB":          {"min": 3.05,      "max": 4.3},
            "LYS_DR":      {"min": 1.00,      "max": None},
            "MET_DR":      {"min": 0.41,      "max": None},
            "M+C_DR":      {"min": 0.76,      "max": None},
            "THR_DR":      {"min": 0.66,      "max": None},
            "TRP_DR":      {"min": 0.18,      "max": None},
            "ILE_DR":      {"min": 0.68,      "max": None},
            "VAL_DR":      {"min": 0.79,      "max": None},
            "ARG_DR":      {"min": 1.06,      "max": None},
            "Ca":          {"min": 0.75,      "max": 0.85},
            "P":           {"min": 0.56,      "max": None},
            "Pdisp.AVES":  {"min": 0.38,      "max": None},
            "Na":          {"min": 0.16,      "max": 0.19},
            "K":           {"min": 0.46,      "max": 1.05},
            "Cl":          {"min": 0.16,      "max": 0.32},
            "Zn":          {"min": 65,        "max": 80},
            "Cu":          {"min": 7,         "max": 8},
            "Mn":          {"min": 70,        "max": 105},
            "Fe":          {"min": 30,        "max": 40},
            "Vit. E":      {"min": 15,        "max": 40},
            "Colina":      {"min": 0.120,     "max": 0.120},
            "Biotina":     {"min": 0.000010,  "max": 0.000013},
        },
        "Broiler Acabado": {
            "EMA_AVES":    {"min": 3120,      "max": 3120},
            "PB":          {"min": 17.5,      "max": None},
            "FB":          {"min": 3.05,      "max": 4.4},
            "LYS_DR":      {"min": 0.92,      "max": None},
            "MET_DR":      {"min": 0.38,      "max": None},
            "M+C_DR":      {"min": 0.70,      "max": None},
            "THR_DR":      {"min": 0.61,      "max": None},
            "TRP_DR":      {"min": 0.17,      "max": None},
            "ILE_DR":      {"min": 0.63,      "max": None},
            "VAL_DR":      {"min": 0.73,      "max": None},
            "ARG_DR":      {"min": 0.98,      "max": None},
            "Ca":          {"min": 0.70,      "max": 0.80},
            "P":           {"min": 0.52,      "max": None},
            "Pdisp.AVES":  {"min": 0.35,      "max": None},
            "Na":          {"min": 0.15,      "max": 0.18},
            "K":           {"min": 0.40,      "max": 1.00},
            "Cl":          {"min": 0.15,      "max": 0.32},
            "Zn":          {"min": 45,        "max": 65},
            "Cu":          {"min": 4,         "max": 8},
            "Mn":          {"min": 55,        "max": 80},
            "Fe":          {"min": 25,        "max": 30},
            "Vit. E":      {"min": 12,        "max": 30},
            "Colina":      {"min": 0.110,     "max": 0.110},
            "Biotina":     {"min": 0.000001,  "max": 0.000003},
        },
    },
    "Cerdos": {
        "Crecimiento": {
            "PB":          {"min": 18.0,  "max": 22.0},
            "EE":          {"min": 2.0,   "max": None},
            "FB":          {"min": None,  "max": 8.0},
            "LYS_DR":      {"min": 0.95,  "max": None},
            "MET_DR":      {"min": 0.26,  "max": None},
            "M+C_DR":      {"min": 0.54,  "max": None},
            "THR_DR":      {"min": 0.61,  "max": None},
            "TRP_DR":      {"min": 0.17,  "max": None},
            "Ca":          {"min": 0.65,  "max": 0.85},
            "P":           {"min": 0.55,  "max": None},
            "Na":          {"min": 0.15,  "max": 0.25},
        },
        "Engorde": {
            "PB":          {"min": 16.0,  "max": 20.0},
            "EE":          {"min": 2.0,   "max": None},
            "FB":          {"min": None,  "max": 8.0},
            "LYS_DR":      {"min": 0.75,  "max": None},
            "MET_DR":      {"min": 0.22,  "max": None},
            "M+C_DR":      {"min": 0.45,  "max": None},
            "THR_DR":      {"min": 0.50,  "max": None},
            "TRP_DR":      {"min": 0.14,  "max": None},
            "Ca":          {"min": 0.55,  "max": 0.75},
            "P":           {"min": 0.50,  "max": None},
            "Na":          {"min": 0.15,  "max": 0.25},
        },
        "Reproductoras": {
            "PB":          {"min": 14.0,  "max": 16.0},
            "FB":          {"min": None,  "max": 10.0},
            "LYS_DR":      {"min": 0.70,  "max": None},
            "MET_DR":      {"min": 0.20,  "max": None},
            "M+C_DR":      {"min": 0.40,  "max": None},
            "THR_DR":      {"min": 0.48,  "max": None},
            "TRP_DR":      {"min": 0.13,  "max": None},
            "Ca":          {"min": 0.75,  "max": 1.0},
            "P":           {"min": 0.60,  "max": None},
            "Na":          {"min": 0.15,  "max": 0.20},
        },
    },
    "Rumiantes": {
        "Terneros": {
            "PB":          {"min": 16.0,  "max": 20.0},
            "EE":          {"min": 2.0,   "max": None},
            "FB":          {"min": 12.0,  "max": None},
            "Ca":          {"min": 0.65,  "max": 1.0},
            "P":           {"min": 0.40,  "max": None},
            "Na":          {"min": 0.10,  "max": 0.20},
        },
        "Vacas lecheras": {
            "PB":          {"min": 16.0,  "max": 18.0},
            "EE":          {"min": 3.0,   "max": 6.0},
            "FB":          {"min": 17.0,  "max": 25.0},
            "Ca":          {"min": 0.60,  "max": 1.0},
            "P":           {"min": 0.35,  "max": None},
            "Na":          {"min": 0.18,  "max": 0.25},
        },
        "Vacas secas": {
            "PB":          {"min": 12.0,  "max": 14.0},
            "EE":          {"min": 2.0,   "max": None},
            "FB":          {"min": 18.0,  "max": None},
            "Ca":          {"min": 0.40,  "max": 0.60},
            "P":           {"min": 0.20,  "max": None},
            "Na":          {"min": 0.10,  "max": 0.18},
        },
    },
}
