# ======================== PRESETS DE REQUERIMIENTOS NUTRICIONALES ========================
# Estructura: PRESETS[especie][etapa][nutriente] = {"min": valor, "max": valor}
# Los nutrientes usan los mismos nombres de columna que la matriz de ingredientes.
# Los valores None indican que el límite no aplica para esa especie/etapa.
# Nota: los valores serán ajustados con datos de referencia en fases posteriores.

PRESETS = {
    "Aves": {
        "Pollitos": {
            "PB":          {"min": 22.0,  "max": 24.0},
            "EMA_POLLIT":  {"min": 2800,  "max": 3200},
            "EMA_AVES":    {"min": 2800,  "max": 3200},
            "EE":          {"min": 3.0,   "max": None},
            "FB":          {"min": None,  "max": 5.0},
            "LYS_DR":      {"min": 1.14,  "max": None},
            "MET_DR":      {"min": 0.50,  "max": None},
            "M+C_DR":      {"min": 0.90,  "max": None},
            "THR_DR":      {"min": 0.74,  "max": None},
            "TRP_DR":      {"min": 0.20,  "max": None},
            "Ca":          {"min": 1.0,   "max": 1.2},
            "Pdisp.AVES":  {"min": 0.45,  "max": None},
            "Na":          {"min": 0.16,  "max": 0.23},
        },
        "Pollos de engorde": {
            "PB":          {"min": 18.0,  "max": 22.0},
            "EMA_POLLIT":  {"min": 3100,  "max": 3300},
            "EMA_AVES":    {"min": 3100,  "max": 3300},
            "EE":          {"min": 3.0,   "max": None},
            "FB":          {"min": None,  "max": 5.0},
            "LYS_DR":      {"min": 0.87,  "max": None},
            "MET_DR":      {"min": 0.38,  "max": None},
            "M+C_DR":      {"min": 0.72,  "max": None},
            "THR_DR":      {"min": 0.60,  "max": None},
            "TRP_DR":      {"min": 0.17,  "max": None},
            "Ca":          {"min": 0.8,   "max": 1.0},
            "Pdisp.AVES":  {"min": 0.35,  "max": None},
            "Na":          {"min": 0.16,  "max": 0.23},
        },
        "Reproductoras": {
            "PB":          {"min": 15.0,  "max": 18.0},
            "EMA_AVES":    {"min": 2750,  "max": 2900},
            "FB":          {"min": None,  "max": 6.0},
            "LYS_DR":      {"min": 0.65,  "max": None},
            "MET_DR":      {"min": 0.30,  "max": None},
            "M+C_DR":      {"min": 0.57,  "max": None},
            "Ca":          {"min": 3.0,   "max": 4.5},
            "Pdisp.AVES":  {"min": 0.35,  "max": None},
            "Na":          {"min": 0.15,  "max": 0.20},
        },
    },
    "Cerdos": {
        "Crecimiento": {
            "PB":          {"min": 18.0,  "max": 22.0},
            "EE":          {"min": 2.0,   "max": None},
            "FB":          {"min": None,  "max": 8.0},
            "LYS_DR":      {"min": 0.95,  "max": None},
            "MET_DR":      {"min": 0.26,  "max": None},
            "M+C_DR":      {"min": 0.54,  "max": None},
            "THR_DR":      {"min": 0.61,  "max": None},
            "TRP_DR":      {"min": 0.17,  "max": None},
            "Ca":          {"min": 0.65,  "max": 0.85},
            "P":           {"min": 0.55,  "max": None},
            "Na":          {"min": 0.15,  "max": 0.25},
        },
        "Engorde": {
            "PB":          {"min": 16.0,  "max": 20.0},
            "EE":          {"min": 2.0,   "max": None},
            "FB":          {"min": None,  "max": 8.0},
            "LYS_DR":      {"min": 0.75,  "max": None},
            "MET_DR":      {"min": 0.22,  "max": None},
            "M+C_DR":      {"min": 0.45,  "max": None},
            "THR_DR":      {"min": 0.50,  "max": None},
            "TRP_DR":      {"min": 0.14,  "max": None},
            "Ca":          {"min": 0.55,  "max": 0.75},
            "P":           {"min": 0.50,  "max": None},
            "Na":          {"min": 0.15,  "max": 0.25},
        },
        "Reproductoras": {
            "PB":          {"min": 14.0,  "max": 16.0},
            "FB":          {"min": None,  "max": 10.0},
            "LYS_DR":      {"min": 0.70,  "max": None},
            "MET_DR":      {"min": 0.20,  "max": None},
            "M+C_DR":      {"min": 0.40,  "max": None},
            "THR_DR":      {"min": 0.48,  "max": None},
            "TRP_DR":      {"min": 0.13,  "max": None},
            "Ca":          {"min": 0.75,  "max": 1.0},
            "P":           {"min": 0.60,  "max": None},
            "Na":          {"min": 0.15,  "max": 0.20},
        },
    },
    "Rumiantes": {
        "Terneros": {
            "PB":          {"min": 16.0,  "max": 20.0},
            "EE":          {"min": 2.0,   "max": None},
            "FB":          {"min": 12.0,  "max": None},
            "Ca":          {"min": 0.65,  "max": 1.0},
            "P":           {"min": 0.40,  "max": None},
            "Na":          {"min": 0.10,  "max": 0.20},
        },
        "Vacas lecheras": {
            "PB":          {"min": 16.0,  "max": 18.0},
            "EE":          {"min": 3.0,   "max": 6.0},
            "FB":          {"min": 17.0,  "max": 25.0},
            "Ca":          {"min": 0.60,  "max": 1.0},
            "P":           {"min": 0.35,  "max": None},
            "Na":          {"min": 0.18,  "max": 0.25},
        },
        "Vacas secas": {
            "PB":          {"min": 12.0,  "max": 14.0},
            "EE":          {"min": 2.0,   "max": None},
            "FB":          {"min": 18.0,  "max": None},
            "Ca":          {"min": 0.40,  "max": 0.60},
            "P":           {"min": 0.20,  "max": None},
            "Na":          {"min": 0.10,  "max": 0.18},
        },
    },
}
